GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ncyran;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO ncyran;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA  public TO ncyran;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ncyran;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO ncyran;

